### PR TITLE
path.existsSync doesn't exist in version 6.11.3

### PR DESCRIPTION
**Pull request by mlbright**

### CODE REVIEW

**Comment by eblume** [comment]
Wow, are you using gmail_safe in the wild? I haven't touched this code in a long, long time. Are you pretty sure your change fixes this issue?

**Comment by mlbright** [comment]
Thanks! It works for me. I'm using gmail_safe to retrieve all my gmail email. I'm doing this for backup purposes, but also because I think it's nice to be able to grep mail locally. I also tried https://github.com/amenonsen/gmail-mirror, which was also quite fast, but had perl deprecation warnings. (I'm trying to fix these.)

More generally, what do you use to retrieve all your mail locally (if you do this)? I would like to do this with my workplace email too, which I also believe exposes an IMAP interface.

**Comment by eblume** [comment]
It's been a while since I looked in to this - to be honest, I simply became
satisfied the gmail was as stable a data store as I have access to.
gmail_safe started out as a project to learn node.js, and that's all it
ever really was. I do regret publishing it on npm, I was younger and didn't
realize that there are some social obligations to publishing code.

**Comment by mlbright** [comment]
No worries! Your code is much appreciated.

**Pull request merged**
